pretrained_t2v_path: "showlab/show-1-base"
vid_name: "rabbit_strawberry"
logdir: "./outputs"
train_steps: 500
validation_steps: 100
seed: 12345
lr: 1e-4
trainable_modules:
  - ".to_q"
  - ".to_k"
  - ".to_v"
num_inv_steps: 75
threshold: 0.2
save_config: True
sr2_strength: 0.8
sr2_steps: 50
ld_global: 0.4
ld_local: 0.2
num_levels: 3
ld_levels: [1., 1., 1., 1.]

train_dataset:
  path: "video_images/${..vid_name}"
  prompt: "a rabbit is eating strawberries"
  n_sample_frame: 8
  sampling_rate: 1
  stride: 1

validation_sample_logger:
  prompts: [
    "a hamster is eating nuts",
    "a hamster is eating strawberries",
    "a raccoon is eating nuts",
    "a squirrel is eating nuts",
    "a squirrel is eating cherries",
  ]
  clip_length: "${..train_dataset.n_sample_frame}"
  sample_seeds: [12345]
  num_inference_steps: 75
  guidance_scale: 9.0
  height: 40
  width: 64
